-- SharedRide v0.2 database schema
-- Run this entire file in Supabase Dashboard -> SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.rides (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  pickup text not null,
  destination text not null,
  departure_time timestamptz not null,
  estimated_fare integer not null check (estimated_fare > 0),
  seats_total integer not null default 2 check (seats_total between 1 and 6),
  seats_available integer not null default 1 check (seats_available between 0 and 6),
  status text not null default 'open' check (status in ('open','full','closed')),
  created_at timestamptz not null default now()
);

create table if not exists public.ride_members (
  id bigint generated by default as identity primary key,
  ride_id uuid not null references public.rides(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner','member')),
  joined_at timestamptz not null default now(),
  unique (ride_id, user_id)
);

alter table public.rides enable row level security;
alter table public.ride_members enable row level security;

drop policy if exists "Anyone can view open rides" on public.rides;
create policy "Anyone can view open rides" on public.rides
for select using (status in ('open','full') or auth.uid() = user_id);

drop policy if exists "Users can create their own rides" on public.rides;
create policy "Users can create their own rides" on public.rides
for insert with check (auth.uid() = user_id);

drop policy if exists "Owners can update their rides" on public.rides;
create policy "Owners can update their rides" on public.rides
for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Owners can delete their rides" on public.rides;
create policy "Owners can delete their rides" on public.rides
for delete using (auth.uid() = user_id);

drop policy if exists "Members can view memberships" on public.ride_members;
create policy "Members can view memberships" on public.ride_members
for select using (true);

drop policy if exists "Users can join as themselves" on public.ride_members;
create policy "Users can join as themselves" on public.ride_members
for insert with check (auth.uid() = user_id);

drop policy if exists "Users can leave their own membership" on public.ride_members;
create policy "Users can leave their own membership" on public.ride_members
for delete using (auth.uid() = user_id);

create index if not exists rides_departure_time_idx on public.rides(departure_time);
create index if not exists rides_pickup_idx on public.rides(lower(pickup));
create index if not exists rides_destination_idx on public.rides(lower(destination));
create index if not exists ride_members_ride_idx on public.ride_members(ride_id);

-- Optional seed data. Remove this section if you want an empty production database.
-- These rows cannot be inserted without a real auth user, so the app itself should create the first ride.
